repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.safety-project\.ini$
      - id: end-of-file-fixer
        exclude: ^\.safety-project\.ini$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # All local hooks that use project dependencies from pyproject.toml
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: Run mypy static type checker with project dependencies
        entry: bash -c 'pip install -e ".[lint]" > /dev/null && python -m mypy --config-file=pyproject.toml fast_api_template'
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true

      - id: vulture
        name: vulture
        description: Run vulture to find unused code with project dependencies
        entry: bash -c 'pip install -e ".[lint]" > /dev/null && python -m vulture --min-confidence=80 fast_api_template tests'
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true

      - id: ruff-lint
        name: ruff linter
        description: Run ruff linter with project dependencies
        entry: bash -c 'pip install -e ".[lint]" > /dev/null && python -m ruff check --fix --unsafe-fixes --line-length=120 .'
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff formatter
        description: Run ruff formatter with project dependencies
        entry: bash -c 'pip install -e ".[lint]" > /dev/null && python -m ruff format --line-length=120 .'
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true

      - id: security-check
        name: Dependency Security Check
        entry: python scripts/check_dependencies.py
        language: system
        pass_filenames: false
        files: pyproject.toml
        require_serial: true
        stages: [pre-commit]
        always_run: true
        # Note: This hook doesn't actually modify files, even if pre-commit reports it does

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, css, scss, html]
        args: [--print-width=120]

  # Temporarily disable interrogate until we improve docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--fail-under=30, --verbose] # Lowered requirement temporarily
        exclude: ^(tests/|docs/|setup.py)
