repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.safety-project\.ini$
      - id: end-of-file-fixer
        exclude: ^\.safety-project\.ini$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes, --line-length=120]
      - id: ruff-format
        args: [--line-length=120]

  # Add proper type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        exclude: "stubs/.*"
        additional_dependencies:
          [
            types-requests,
            pydantic,
            types-python-jose,
            types-passlib,
            types-redis,
            types-boto3,
            types-docker,
            boto3-stubs,
            mypy-boto3-s3,
            mypy-boto3-sqs,
          ]
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10
    hooks:
      - id: vulture
        args: ["--min-confidence=80"]
        additional_dependencies: []
        always_run: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, css, scss, html]
        args: [--print-width=120]

  # Custom hook for dependency security checking that works with pyproject.toml
  - repo: local
    hooks:
      - id: security-check
        name: Dependency Security Check
        entry: python scripts/check_dependencies.py
        language: system
        pass_filenames: false
        files: pyproject.toml
        require_serial: true
        stages: [pre-commit]
        always_run: true
        # Note: This hook doesn't actually modify files, even if pre-commit reports it does

  # Temporarily disable interrogate until we improve docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--fail-under=30, --verbose] # Lowered requirement temporarily
        exclude: ^(tests/|docs/|setup.py)
