[development]
database = { url = "sqlite:///dev.db", echo = false }
jwt = { secret_key = "dev_secret_key", algorithm = "HS256", access_token_expire_minutes = 30 }
server = { name = "Development Server", description = "Development Description", version = "1.0.0", docs_url = "/docs" }
cors = { origins = ["http://localhost:3000"] }
demo_user = { password_hash = "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj1ZxQQxq3re" }

[testing]
database = { url = "sqlite:///test.db", echo = false }
jwt = { secret_key = "test_secret_key", algorithm = "HS256", access_token_expire_minutes = 30 }
server = { name = "Test Server", description = "Test Description", version = "1.0.0", docs_url = "/docs" }
cors = { origins = ["http://localhost:3000"] }
demo_user = { password_hash = "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj1ZxQQxq3re" }
