version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - fast_api_template_DB__uri=postgresql://postgres:postgres@db:5432/fast_api_template
      - fast_api_template_DB__connect_args={}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 2

  db:
    build: postgres
    image: fast_api_template_postgres-13-alpine-multi-user
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_DBS=fast_api_template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    secrets:
      - db_password
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

volumes:
  postgres_data:
    name: fast_api_template_db_data
    driver: local

secrets:
  db_password:
    file: ./secrets/db_password.txt
