version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - fast_api_template_DB__uri=postgresql://postgres:postgres@db:5432/fast_api_template
      - fast_api_template_DB__connect_args={}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./fast_api_template:/home/app/web/fast_api_template
      - ./pyproject.toml:/home/app/web/pyproject.toml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    build: postgres
    image: fast_api_template_postgres-13-alpine-multi-user
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DBS=fast_api_template, fast_api_template_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
    name: fast_api_template_db_data
