site_name: Fast API Template
site_description: A modern FastAPI project template with best practices
site_author: sm4rtm4art
repo_url: https://github.com/sm4rtm4art/FAST_API_TEMPLATE
repo_name: sm4rtm4art/FAST_API_TEMPLATE

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Installation: guide/installation.md
    - Configuration: guide/configuration.md
    - Development: guide/development.md
    - Deployment: guide/deployment.md
    - CI/CD: guide/ci-cd.md
  - API Reference: api-reference.md
  - Project Structure: PROJECT_STRUCTURE.md
  - Contributing: CONTRIBUTING.md
  - Changelog: HISTORY.md
