[default]
server.name = "FastAPI Template"
server.description = "A FastAPI template with authentication and cloud services"
server.version = "0.1.0"
server.docs_url = "/docs"
server.port = 8000
server.host = "0.0.0.0"
server.log_level = "info"
server.reload = false
server.cors_origins = ["*"]

database.echo = false
database.url = "sqlite:///./test.db"

jwt.secret_key = "your-secret-key"
jwt.algorithm = "HS256"
jwt.access_token_expire_minutes = 30

cloud.provider = "aws"

[development]
server.log_level = "debug"
server.reload = true
server.cors_origins = ["http://localhost:3000"]

database.echo = true

[production]
server.log_level = "error"
server.reload = false
server.cors_origins = ["https://yourdomain.com"]

[testing]
server.cors_origins = ["http://localhost:3000"]
database.url = "sqlite:///./test.db"
