# Minimal GitLab CI configuration that includes the main config from .ci directory
# This keeps the root directory clean while still supporting GitLab CI

include:
  - local: ".gitlab-ci-main.yml"

# Define minimal variables needed before including the main config
variables:
  PYTHON_VERSION: "3.12"
